package org.shikshalokam.job.survey.stream.processor.task

import com.typesafe.config.Config
import org.apache.flink.api.common.typeinfo.TypeInformation
import org.apache.flink.api.java.typeutils.TypeExtractor
import org.apache.flink.streaming.api.scala.OutputTag
import org.shikshalokam.job.survey.stream.processor.domain.Event
import org.shikshalokam.job.BaseJobConfig
import scala.collection.JavaConverters._

class SurveyStreamConfig(override val config: Config) extends BaseJobConfig(config, "SurveysStreamJob") {

  implicit val mapTypeInfo: TypeInformation[Event] = TypeExtractor.getForClass(classOf[Event])

  // Kafka Topics Configuration
  val inputTopic: String = config.getString("kafka.input.topic")
  val outputTopic: String = config.getString("kafka.output.topic")

  // Output Tags
  val eventOutputTag: OutputTag[String] = OutputTag[String]("survey-dashboard-output-event")

  // Parallelism
  override val kafkaConsumerParallelism: Int = config.getInt("task.consumer.parallelism")
  val surveysStreamParallelism: Int = config.getInt("task.sl.surveys.stream.parallelism")
  val metabaseDashboardParallelism: Int = config.getInt("task.sl.metabase.dashboard.parallelism")

  // Consumers
  val surveysStreamConsumer: String = "survey-stream-consumer"
  val metabaseDashboardProducer = "metabase-dashboard-producer"

  // Functions
  val surveysStreamFunction: String = "SurveyStreamFunction"

  // Survey submissions job metrics
  val surveysCleanupHit = "survey-cleanup-hit"
  val skipCount = "skipped-message-count"
  val successCount = "success-message-count"
  val totalEventsCount = "total-survey-events-count"

  //report-config
  val reportsEnabled: Set[String] = config.getStringList("reports.enabled").asScala.toSet

  // PostgreSQL connection config
  val pgHost: String = config.getString("postgres.host")
  val pgPort: String = config.getString("postgres.port")
  val pgUsername: String = config.getString("postgres.username")
  val pgPassword: String = config.getString("postgres.password")
  val pgDataBase: String = config.getString("postgres.database")
  val solutions: String = config.getString("postgres.tables.solutionsTable")
  val dashboard_metadata: String = config.getString("postgres.tables.dashboardMetadataTable")

  val createSolutionsTable: String =
    s"""CREATE TABLE IF NOT EXISTS $solutions (
       |    solution_id TEXT PRIMARY KEY,
       |    external_id TEXT,
       |    name TEXT,
       |    description TEXT,
       |    duration TEXT,
       |    categories TEXT,
       |    program_id TEXT,
       |    program_name TEXT,
       |    program_external_id TEXT,
       |    program_description TEXT,
       |    private_program BOOLEAN,
       |    org_id TEXT
       |);""".stripMargin

  val createDashboardMetadataTable: String =
    s"""CREATE TABLE IF NOT EXISTS $dashboard_metadata (
       |    id SERIAL PRIMARY KEY,
       |    entity_type TEXT NOT NULL,
       |    entity_name TEXT NOT NULL,
       |    entity_id TEXT UNIQUE NOT NULL,
       |    report_type TEXT,
       |    is_rubrics Boolean,
       |    parent_name TEXT,
       |    linked_to TEXT,
       |    main_metadata JSON,
       |    mi_metadata JSON,
       |    comparison_metadata JSON,
       |    status TEXT,
       |    error_message TEXT,
       |    state_details_url_state TEXT,
       |    state_details_url_admin TEXT,
       |    district_details_url_district TEXT,
       |    district_details_url_state TEXT,
       |    district_details_url_admin TEXT
       |);
       |""".stripMargin

  val createSurveyStatusTableQuery: String =
    s"""CREATE TABLE IF NOT EXISTS @surveyStatusTable (
       |    survey_id TEXT PRIMARY KEY,
       |    user_id TEXT,
       |    user_role_ids TEXT,
       |    user_roles TEXT,
       |    state_id TEXT,
       |    state_name TEXT,
       |    district_id TEXT,
       |    district_name TEXT,
       |    block_id TEXT,
       |    block_name TEXT,
       |    cluster_id TEXT,
       |    cluster_name TEXT,
       |    school_id TEXT,
       |    school_name TEXT,
       |    tenant_id TEXT,
       |    organisation_id TEXT,
       |    organisation_name TEXT,
       |    organisation_code TEXT,
       |    program_name TEXT,
       |    program_id TEXT,
       |    solution_name TEXT,
       |    solution_id TEXT,
       |    status TEXT,
       |    submission_date TEXT
       |);""".stripMargin

  val createSurveyQuestionsTableQuery: String =
    s"""CREATE TABLE IF NOT EXISTS "@surveyQuestionTable" (
       |    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       |    survey_id TEXT,
       |    user_id TEXT,
       |    user_role_ids TEXT,
       |    user_roles TEXT,
       |    state_id TEXT,
       |    state_name TEXT,
       |    district_id TEXT,
       |    district_name TEXT,
       |    block_id TEXT,
       |    block_name TEXT,
       |    cluster_id TEXT,
       |    cluster_name TEXT,
       |    school_id TEXT,
       |    school_name TEXT,
       |    tenant_id TEXT,
       |    organisation_id TEXT,
       |    organisation_name TEXT,
       |    organisation_code TEXT,
       |    program_name TEXT,
       |    program_id TEXT,
       |    solution_name TEXT,
       |    solution_id TEXT,
       |    question_id TEXT,
       |    question_text TEXT,
       |    question_type TEXT,
       |    labels TEXT,
       |    value TEXT,
       |    has_parent_question BOOLEAN,
       |    parent_question_text TEXT,
       |    report_type TEXT,
       |    evidence TEXT,
       |    remarks TEXT
       |);""".stripMargin

}