# Copy this file to config.ini and fill in the values before running the scripts.  
# cp sample.ini config.ini  
[POSTGRES_DB]
HOST = {{POSTGRES_HOST}}
PORT = {{POSTGRES_PORT}}
ELEVATE_DBNAME = {{POSTGRES_DB}}
USER = {{POSTGRES_USER}}
PASSWORD = {{POSTGRES_PASSWORD}}
METADATA_TABLE = {{METADATA_TABLE}}
USERS_DBNAME = {{USERS_DBNAME}}  #This is the user database name that is used in user service
USERS_TABLE = users

[API]
ENTITY_API = {{ENTITY_API}}  #Base URL is the API URL of the {{backend-service}}/entity-management/v1/entities/find
INTERNAL_TOKEN = {{INTERNAL_TOKEN}}  #Access token from the login api of org_admin role user

[KAFKA]
BROKER = {{KAFKA_BROKER}}
TOPIC_PROJECT = {{TOPIC_PROJECT}}  #Keep the project dashboard topic name 
TOPIC_SURVEY = {{TOPIC_SURVEY}}  #Keep the survey dashboard topic name 
TOPIC_OBSERVATION = {{TOPIC_OBSERVATION}} #Keep the observation dashboard topic name 
TOPIC_USER = {{TOPIC_USER}} #Keep the user dashboard topic name 
