# Copy this file to config.ini and fill in the values before running the scripts.  
# cp sample.ini config.ini  
[POSTGRES_DB]
HOST = {{POSTGRES_HOST}}
PORT = {{POSTGRES_PORT}}
ELEVATE_DBNAME = {{POSTGRES_DB}}
USER = {{POSTGRES_USER}}
PASSWORD = {{POSTGRES_PASSWORD}}
METADATA_TABLE = {{METADATA_TABLE}}
USERS_DBNAME = {{USERS_DBNAME}}
USERS_TABLE = {{USERS_TABLE}}

[API]
ENTITY_API = {{ENTITY_API}}
INTERNAL_TOKEN = {{INTERNAL_TOKEN}}

[KAFKA]
BROKER = {{KAFKA_BROKER}}
TOPIC_PROJECT = {{TOPIC_PROJECT}}
TOPIC_SURVEY = {{TOPIC_SURVEY}}
TOPIC_OBSERVATION = {{TOPIC_OBSERVATION}}
TOPIC_USER = {{TOPIC_USER}}
