include "base-config.conf"

kafka {
  # groupId = "dummy-unified-group"
  input {
    project {
      enabled = true
      topic = "sl-improvement-project-submission-prod"
    }
    survey {
      enabled = true
      topic  = "elevate_surveys_raw_prod"
    }
    observation {
      enabled = true
      topic = "sl-improvement-observation-submission-prod"
    }
    user {
      enabled = true
      topic = "sl-improvement-user-submission-prod"
    }
    mentoring {
      enabled = true
      topic = "sl-improvement-mentoring-submission-prod"
    }
  }
  output {
    project.topic = "sl-metabase-project-dashboard-prod"
    survey.topic  = "sl-metabase-survey-dashboard-prod"
    observation.topic = "sl-metabase-observation-dashboard-prod"
    user.topic = "sl-metabase-user-dashboard-prod"
    mentoring.topic = "sl-metabase-mentoring-dashboard-prod"
  }
  consumer {
    project.group = "sl-improvement-project-consumer-group-prod"
    survey.group  = "elevate-survey-raw-consumer-group-prod"
    observation.group = "sl-improvement-observation-consumer-group-prod"
    user.group = "sl-improvement-user-consumer-group-prod"
    mentoring.group = "sl-improvement-mentoring-consumer-group-prod"
  }
}

task {
  project {
    consumer.parallelism = 1
    process.parallelism = 1
    sink.parallelism = 1
  }
  survey {
    consumer.parallelism = 1
    process.parallelism = 1
    sink.parallelism = 1
  }
  observation {
    consumer.parallelism = 1
    process.parallelism = 1
    sink.parallelism = 1
  }
  user {
    consumer.parallelism = 1
    process.parallelism = 1
    sink.parallelism = 1
  }
  mentoring {
    consumer.parallelism = 1
    process.parallelism = 1
    sink.parallelism = 1
  }
}

test.mode = true

postgres{
  host = "localhost"
  port = "5432"
  username = "postgres"
  password = "postgres"
  database = "test"
  tables = {
    solutionsTable = ${job.env}"_solutions"
    projectsTable = ${job.env}"_projects"
    tasksTable = ${job.env}"_tasks"
    dashboardMetadataTable = ${job.env}"_dashboard_metadata"
    userMetrics = ${job.env}"_user_metrics"
  }
}

reports{
  enabled = ["admin", "state", "district", "program", "solution"]
}