services {
  flink {
    rest-api-url = "https://flink-qa.tekdinext.com"
    jobs = [
      "MetabaseProjectDashboardJob",
      "ProjectsStreamJob",
      "SurveysStreamJob",
      "MetabaseSurveyDashboardJob",
      "UserAndProgramManagement",
      "ObservationsStreamJob",
      "MetabaseObservationDashboardJob",
      "UsersStreamJob",
      "MentoringStreamJob",
      "MetabaseUserDashboardJob",
      "MetabaseMentoringDashboardJob"
    ]
  }

  kafka {
    broker-list = "localhost:9093"
  }

  metabase {
    url = "https://qa.elevate.metabase.shikshalokam.org"
  }
}
