kafka {
  broker-servers = "kafka:9092"
  zookeeper = "zookeeper:2181"
  groupId = "combined-dashboard-creator-group"
  max.poll.interval.ms = "600000"
  max.poll.records = "50"
}

job {
  env = "dev"
  bb = "elevate"
  enable.distributed.checkpointing = true
  statebackend {
    blob {
      storage {
        account = "blob.storage.account"
        container = "kp-checkpoints"
        checkpointing.dir = "flink-jobs"
      }
    }
    base.url = "file:///opt/flink/checkpoints"
  }
}

task {
  checkpointing.compressed = true
  checkpointing.pause.between.seconds = 30000
  parallelism = 1
  checkpointing.interval = 60000
  restart-strategy.attempts = 3
  restart-strategy.delay = 30000 # in milli-seconds
  consumer.parallelism = 1
}