rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.rolling.ref = RollingFileAppender

# Console Appender
appender.console.name = ConsoleAppender
appender.console.type = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

# Main Rolling File Appender (for everything else)
appender.rolling.name = RollingFileAppender
appender.rolling.type = RollingFile
appender.rolling.fileName = ${sys:log.file}
appender.rolling.filePattern = ${sys:log.file}.%i
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 100MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 10

# Project Stream Appender
appender.project.name = ProjectFileAppender
appender.project.type = RollingFile
appender.project.fileName = logs/project-stream.log
appender.project.filePattern = logs/project-stream-%d{yyyy-MM-dd}.log.gz
appender.project.layout.type = PatternLayout
appender.project.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.project.policies.type = Policies
appender.project.policies.time.type = TimeBasedTriggeringPolicy
appender.project.policies.time.interval = 1
appender.project.policies.time.modulate = true
appender.project.strategy.type = DefaultRolloverStrategy
appender.project.strategy.delete.type = Delete
appender.project.strategy.delete.basePath = logs
appender.project.strategy.delete.maxDepth = 1
appender.project.strategy.delete.ifFileName.type = IfFileName  
appender.project.strategy.delete.ifFileName.glob = project-stream-*.log.gz  
appender.project.strategy.delete.ifLastModified.type = IfLastModified
appender.project.strategy.delete.ifLastModified.age = 7d

# Survey Stream Appender
appender.survey.name = SurveyFileAppender
appender.survey.type = RollingFile
appender.survey.fileName = logs/survey-stream.log
appender.survey.filePattern = logs/survey-stream-%d{yyyy-MM-dd}.log.gz
appender.survey.layout.type = PatternLayout
appender.survey.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.survey.policies.type = Policies
appender.survey.policies.time.type = TimeBasedTriggeringPolicy
appender.survey.policies.time.interval = 1
appender.survey.policies.time.modulate = true
appender.survey.strategy.type = DefaultRolloverStrategy
appender.survey.strategy.delete.type = Delete
appender.survey.strategy.delete.basePath = logs
appender.survey.strategy.delete.maxDepth = 1
appender.survey.strategy.delete.ifFileName.type = IfFileName  
appender.survey.strategy.delete.ifFileName.glob = survey-stream-*.log.gz  
appender.survey.strategy.delete.ifLastModified.type = IfLastModified
appender.survey.strategy.delete.ifLastModified.age = 7d

# Observation Stream Appender
appender.observation.name = ObservationFileAppender
appender.observation.type = RollingFile
appender.observation.fileName = logs/observation-stream.log
appender.observation.filePattern = logs/observation-stream-%d{yyyy-MM-dd}.log.gz
appender.observation.layout.type = PatternLayout
appender.observation.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.observation.policies.type = Policies
appender.observation.policies.time.type = TimeBasedTriggeringPolicy
appender.observation.policies.time.interval = 1
appender.observation.policies.time.modulate = true
appender.observation.strategy.type = DefaultRolloverStrategy
appender.observation.strategy.delete.type = Delete
appender.observation.strategy.delete.basePath = logs
appender.observation.strategy.delete.maxDepth = 1
appender.observation.strategy.delete.ifFileName.type = IfFileName  
appender.observation.strategy.delete.ifFileName.glob = observation-stream-*.log.gz  
appender.observation.strategy.delete.ifLastModified.type = IfLastModified
appender.observation.strategy.delete.ifLastModified.age = 7d

# User Stream Appender
appender.user.name = UserFileAppender
appender.user.type = RollingFile
appender.user.fileName = logs/user-stream.log
appender.user.filePattern = logs/user-stream-%d{yyyy-MM-dd}.log.gz
appender.user.layout.type = PatternLayout
appender.user.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.user.policies.type = Policies
appender.user.policies.time.type = TimeBasedTriggeringPolicy
appender.user.policies.time.interval = 1
appender.user.policies.time.modulate = true
appender.user.strategy.type = DefaultRolloverStrategy
appender.user.strategy.delete.type = Delete
appender.user.strategy.delete.basePath = logs
appender.user.strategy.delete.maxDepth = 1
appender.user.strategy.delete.ifFileName.type = IfFileName
appender.user.strategy.delete.ifFileName.glob = user-stream-*.log.gz
appender.user.strategy.delete.ifLastModified.type = IfLastModified
appender.user.strategy.delete.ifLastModified.age = 7d

# Project Dashboard Appender
appender.projectDashboard.name = ProjectDashboardFileAppender
appender.projectDashboard.type = RollingFile
appender.projectDashboard.fileName = logs/project-dashboard.log
appender.projectDashboard.filePattern = logs/project-dashboard-%d{yyyy-MM-dd}.log.gz
appender.projectDashboard.layout.type = PatternLayout
appender.projectDashboard.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.projectDashboard.policies.type = Policies
appender.projectDashboard.policies.time.type = TimeBasedTriggeringPolicy
appender.projectDashboard.policies.time.interval = 1
appender.projectDashboard.policies.time.modulate = true
appender.projectDashboard.strategy.type = DefaultRolloverStrategy
appender.projectDashboard.strategy.delete.type = Delete
appender.projectDashboard.strategy.delete.basePath = logs
appender.projectDashboard.strategy.delete.maxDepth = 1
appender.projectDashboard.strategy.delete.ifFileName.type = IfFileName
appender.projectDashboard.strategy.delete.ifFileName.glob = project-dashboard-*.log.gz
appender.projectDashboard.strategy.delete.ifLastModified.type = IfLastModified
appender.projectDashboard.strategy.delete.ifLastModified.age = 7d

# Observation Dashboard Appender
appender.observationDashboard.name = ObservationDashboardFileAppender
appender.observationDashboard.type = RollingFile
appender.observationDashboard.fileName = logs/observation-dashboard.log
appender.observationDashboard.filePattern = logs/observation-dashboard-%d{yyyy-MM-dd}.log.gz
appender.observationDashboard.layout.type = PatternLayout
appender.observationDashboard.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.observationDashboard.policies.type = Policies
appender.observationDashboard.policies.time.type = TimeBasedTriggeringPolicy
appender.observationDashboard.policies.time.interval = 1
appender.observationDashboard.policies.time.modulate = true
appender.observationDashboard.strategy.type = DefaultRolloverStrategy
appender.observationDashboard.strategy.delete.type = Delete
appender.observationDashboard.strategy.delete.basePath = logs
appender.observationDashboard.strategy.delete.maxDepth = 1
appender.observationDashboard.strategy.delete.ifFileName.type = IfFileName
appender.observationDashboard.strategy.delete.ifFileName.glob = observation-dashboard-*.log.gz
appender.observationDashboard.strategy.delete.ifLastModified.type = IfLastModified
appender.observationDashboard.strategy.delete.ifLastModified.age = 7d

# Survey Dashboard Appender
appender.surveyDashboard.name = SurveyDashboardFileAppender
appender.surveyDashboard.type = RollingFile
appender.surveyDashboard.fileName = logs/survey-dashboard.log
appender.surveyDashboard.filePattern = logs/survey-dashboard-%d{yyyy-MM-dd}.log.gz
appender.surveyDashboard.layout.type = PatternLayout
appender.surveyDashboard.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.surveyDashboard.policies.type = Policies
appender.surveyDashboard.policies.time.type = TimeBasedTriggeringPolicy
appender.surveyDashboard.policies.time.interval = 1
appender.surveyDashboard.policies.time.modulate = true
appender.surveyDashboard.strategy.type = DefaultRolloverStrategy
appender.surveyDashboard.strategy.delete.type = Delete
appender.surveyDashboard.strategy.delete.basePath = logs
appender.surveyDashboard.strategy.delete.maxDepth = 1
appender.surveyDashboard.strategy.delete.ifFileName.type = IfFileName
appender.surveyDashboard.strategy.delete.ifFileName.glob = survey-dashboard-*.log.gz
appender.surveyDashboard.strategy.delete.ifLastModified.type = IfLastModified
appender.surveyDashboard.strategy.delete.ifLastModified.age = 7d

# Mentoring Dashboard Appender
appender.mentoringDashboard.name = MentoringDashboardFileAppender
appender.mentoringDashboard.type = RollingFile
appender.mentoringDashboard.fileName = logs/mentoring-dashboard.log
appender.mentoringDashboard.filePattern = logs/mentoring-dashboard-%d{yyyy-MM-dd}.log.gz
appender.mentoringDashboard.layout.type = PatternLayout
appender.mentoringDashboard.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.mentoringDashboard.policies.type = Policies
appender.mentoringDashboard.policies.time.type = TimeBasedTriggeringPolicy
appender.mentoringDashboard.policies.time.interval = 1
appender.mentoringDashboard.policies.time.modulate = true
appender.mentoringDashboard.strategy.type = DefaultRolloverStrategy
appender.mentoringDashboard.strategy.delete.type = Delete
appender.mentoringDashboard.strategy.delete.basePath = logs
appender.mentoringDashboard.strategy.delete.maxDepth = 1
appender.mentoringDashboard.strategy.delete.ifFileName.type = IfFileName
appender.mentoringDashboard.strategy.delete.ifFileName.glob = mentoring-dashboard-*.log.gz
appender.mentoringDashboard.strategy.delete.ifLastModified.type = IfLastModified
appender.mentoringDashboard.strategy.delete.ifLastModified.age = 7d

# User Dashboard Appender
appender.userDashboard.name = UserDashboardFileAppender
appender.userDashboard.type = RollingFile
appender.userDashboard.fileName = logs/user-dashboard.log
appender.userDashboard.filePattern = logs/user-dashboard-%d{yyyy-MM-dd}.log.gz
appender.userDashboard.layout.type = PatternLayout
appender.userDashboard.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.userDashboard.policies.type = Policies
appender.userDashboard.policies.time.type = TimeBasedTriggeringPolicy
appender.userDashboard.policies.time.interval = 1
appender.userDashboard.policies.time.modulate = true
appender.userDashboard.strategy.type = DefaultRolloverStrategy
appender.userDashboard.strategy.delete.type = Delete
appender.userDashboard.strategy.delete.basePath = logs
appender.userDashboard.strategy.delete.maxDepth = 1
appender.userDashboard.strategy.delete.ifFileName.type = IfFileName
appender.userDashboard.strategy.delete.ifFileName.glob = user-dashboard-*.log.gz
appender.userDashboard.strategy.delete.ifLastModified.type = IfLastModified
appender.userDashboard.strategy.delete.ifLastModified.age = 7d

# User Service Appender
appender.userService.name = UserServiceFileAppender
appender.userService.type = RollingFile
appender.userService.fileName = logs/user-service-job.log
appender.userService.filePattern = logs/user-service-job-%d{yyyy-MM-dd}.log.gz
appender.userService.layout.type = PatternLayout
appender.userService.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
appender.userService.policies.type = Policies
appender.userService.policies.time.type = TimeBasedTriggeringPolicy
appender.userService.policies.time.interval = 1
appender.userService.policies.time.modulate = true
appender.userService.strategy.type = DefaultRolloverStrategy
appender.userService.strategy.delete.type = Delete
appender.userService.strategy.delete.basePath = logs
appender.userService.strategy.delete.maxDepth = 1
appender.userService.strategy.delete.ifFileName.type = IfFileName
appender.userService.strategy.delete.ifFileName.glob = user-service-job-*.log.gz
appender.userService.strategy.delete.ifLastModified.type = IfLastModified
appender.userService.strategy.delete.ifLastModified.age = 7d

# Logger for User Service
logger.userService.name = org.shikshalokam.job.user.service.functions
logger.userService.level = INFO
logger.userService.additivity = false
logger.userService.appenderRef.userService.ref = UserServiceFileAppender

# Logger for Project Stream
logger.project.name = org.shikshalokam.job.combined.stream.processor.functions.ProjectStreamFunction
logger.project.level = INFO
logger.project.additivity = false
logger.project.appenderRef.project.ref = ProjectFileAppender

# Logger for Survey Stream
logger.survey.name = org.shikshalokam.job.combined.stream.processor.functions.SurveyStreamFunction
logger.survey.level = INFO
logger.survey.additivity = false
logger.survey.appenderRef.survey.ref = SurveyFileAppender

# Logger for Observation Stream
logger.observation.name = org.shikshalokam.job.combined.stream.processor.functions.ObservationStreamFunction
logger.observation.level = INFO
logger.observation.appenderRef.observation.ref = ObservationFileAppender
logger.observation.additivity = false

# Logger for User Stream
logger.user.name = org.shikshalokam.job.combined.stream.processor.functions.UserStreamFunction
logger.user.level = INFO
logger.user.appenderRef.user.ref = UserFileAppender
logger.user.additivity = false

# Logger for Project Dashboard
logger.projectDashboard.name = org.shikshalokam.job.combined.dashboard.creator.functions.project
logger.projectDashboard.level = INFO
logger.projectDashboard.additivity = false
logger.projectDashboard.appenderRef.projectDashboard.ref = ProjectDashboardFileAppender

# Logger for Observation Dashboard
logger.observationDashboard.name = org.shikshalokam.job.combined.dashboard.creator.functions.observation
logger.observationDashboard.level = INFO
logger.observationDashboard.additivity = false
logger.observationDashboard.appenderRef.observationDashboard.ref = ObservationDashboardFileAppender

# Logger for Survey Dashboard
logger.surveyDashboard.name = org.shikshalokam.job.combined.dashboard.creator.functions.survey
logger.surveyDashboard.level = INFO
logger.surveyDashboard.additivity = false
logger.surveyDashboard.appenderRef.surveyDashboard.ref = SurveyDashboardFileAppender

# Logger for Mentoring Dashboard
logger.mentoringDashboard.name = org.shikshalokam.job.combined.dashboard.creator.functions.mentoring
logger.mentoringDashboard.level = INFO
logger.mentoringDashboard.additivity = false
logger.mentoringDashboard.appenderRef.mentoringDashboard.ref = MentoringDashboardFileAppender

# Logger for User Dashboard
logger.userDashboard.name = org.shikshalokam.job.combined.dashboard.creator.functions.user
logger.userDashboard.level = INFO
logger.userDashboard.additivity = false
logger.userDashboard.appenderRef.userDashboard.ref = UserDashboardFileAppender