package org.shikshalokam.job.observation.stream.processor.task

import com.typesafe.config.Config
import org.apache.flink.api.common.typeinfo.TypeInformation
import org.apache.flink.api.java.typeutils.TypeExtractor
import org.apache.flink.streaming.api.scala.OutputTag
import org.shikshalokam.job.observation.stream.processor.domain.Event
import org.shikshalokam.job.BaseJobConfig
import scala.collection.JavaConverters._

class ObservationStreamConfig(override val config: Config) extends BaseJobConfig(config, "ObservationsStreamJob") {

  implicit val mapTypeInfo: TypeInformation[Event] = TypeExtractor.getForClass(classOf[Event])

  // Kafka Topics Configuration
  val inputTopic: String = config.getString("kafka.input.topic")
  val outputTopic: String = config.getString("kafka.output.topic")

  // Output Tags
  val eventOutputTag: OutputTag[String] = OutputTag[String]("observation-dashboard-output-event")

  // Parallelism
  override val kafkaConsumerParallelism: Int = config.getInt("task.consumer.parallelism")
  val observationStreamParallelism: Int = config.getInt("task.sl.observation.stream.parallelism")
  val metabaseDashboardParallelism: Int = config.getInt("task.sl.metabase.observation.dashboard.parallelism")

  // Consumers
  val observationStreamConsumer: String = "observation-stream-consumer"
  val metabaseDashboardProducer = "metabase-observation-dashboard-producer"

  // Functions
  val observationStreamFunction: String = "ObservationStreamFunction"

  // Observation submissions job metrics
  val observationCleanupHit = "observation-cleanup-hit"
  val skipCount = "skipped-message-count"
  val successCount = "success-message-count"
  val totalEventsCount = "total-observation-events-count"

  //report-config
  val reportsEnabled: Set[String]= config.getStringList("reports.enabled").asScala.toSet

  // PostgreSQL connection config
  val pgHost: String = config.getString("postgres.host")
  val pgPort: String = config.getString("postgres.port")
  val pgUsername: String = config.getString("postgres.username")
  val pgPassword: String = config.getString("postgres.password")
  val pgDataBase: String = config.getString("postgres.database")
  val solutions: String = config.getString("postgres.tables.solutionsTable")
  val dashboard_metadata: String = config.getString("postgres.tables.dashboardMetadataTable")

  val createSolutionsTable: String =
    s"""CREATE TABLE IF NOT EXISTS $solutions (
       |    solution_id TEXT PRIMARY KEY,
       |    external_id TEXT,
       |    name TEXT,
       |    description TEXT,
       |    duration TEXT,
       |    categories TEXT,
       |    program_id TEXT,
       |    program_name TEXT,
       |    program_external_id TEXT,
       |    program_description TEXT,
       |    private_program BOOLEAN,
       |    org_id TEXT
       |);""".stripMargin

  val createDashboardMetadataTable: String =
    s"""CREATE TABLE IF NOT EXISTS $dashboard_metadata (
       |    id SERIAL PRIMARY KEY,
       |    entity_type TEXT NOT NULL,
       |    entity_name TEXT NOT NULL,
       |    entity_id TEXT UNIQUE NOT NULL,
       |    report_type TEXT,
       |    is_rubrics Boolean,
       |    parent_name TEXT,
       |    linked_to TEXT,
       |    main_metadata JSON,
       |    mi_metadata JSON,
       |    comparison_metadata JSON,
       |    status TEXT,
       |    error_message TEXT,
       |    state_details_url_state TEXT,
       |    state_details_url_admin TEXT,
       |    district_details_url_district TEXT,
       |    district_details_url_state TEXT,
       |    district_details_url_admin TEXT
       |);
       |""".stripMargin


  val createDomainsTable: String =
    s"""CREATE TABLE IF NOT EXISTS @domainTable (
       |    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       |    user_id TEXT ,
       |    user_role_ids TEXT,
       |    user_roles TEXT,
       |    solution_id TEXT ,
       |    solution_name TEXT,
       |    submission_id TEXT,
       |    submission_number INTEGER,
       |    program_name TEXT,
       |    program_id TEXT,
       |    observation_name TEXT,
       |    observation_id TEXT,
       |    tenant_id TEXT,
       |    org_name TEXT,
       |    org_id TEXT,
       |    org_code TEXT,
       |    user_one_profile_name TEXT,
       |    user_one_profile_id TEXT,
       |    user_two_profile_name TEXT,
       |    user_two_profile_id TEXT,
       |    user_three_profile_name TEXT,
       |    user_three_profile_id TEXT,
       |    user_four_profile_name TEXT,
       |    user_four_profile_id TEXT,
       |    user_five_profile_name TEXT,
       |    user_five_profile_id TEXT,
       |    domain TEXT,
       |    domain_level TEXT,
       |    criteria TEXT,
       |    criteria_level TEXT,
       |    completed_date TEXT,
       |    entity_type TEXT,
       |    entity_id TEXT,
       |    entity_name TEXT,
       |    entity_external_id TEXT,
       |    parent_one_name TEXT,
       |    parent_one_id TEXT,
       |    parent_two_name TEXT,
       |    parent_two_id TEXT,
       |    parent_three_name TEXT,
       |    parent_three_id TEXT,
       |    parent_four_name TEXT,
       |    parent_four_id TEXT,
       |    parent_five_name TEXT,
       |    parent_five_id TEXT
       |);""".stripMargin

  val createQuestionsTable: String =
    s"""CREATE TABLE IF NOT EXISTS @questionTable (
       |    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       |    user_id TEXT ,
       |    user_role_ids TEXT,
       |    user_roles TEXT,
       |    solution_id TEXT ,
       |    solution_name TEXT,
       |    submission_id TEXT,
       |    submission_number INTEGER,
       |    status_of_submission TEXT,
       |    program_name TEXT,
       |    program_id TEXT,
       |    observation_name TEXT,
       |    observation_id TEXT,
       |    tenant_id TEXT,
       |    org_name TEXT,
       |    org_id TEXT,
       |    org_code TEXT,
       |    user_one_profile_name TEXT,
       |    user_one_profile_id TEXT,
       |    user_two_profile_name TEXT,
       |    user_two_profile_id TEXT,
       |    user_three_profile_name TEXT,
       |    user_three_profile_id TEXT,
       |    user_four_profile_name TEXT,
       |    user_four_profile_id TEXT,
       |    user_five_profile_name TEXT,
       |    user_five_profile_id TEXT,
       |    question_id TEXT,
       |    question_text TEXT,
       |    labels TEXT,
       |    value TEXT,
       |    score INTEGER,
       |    report_type TEXT,
       |    domain_name TEXT,
       |    criteria_name TEXT,
       |    has_parent_question BOOLEAN,
       |    parent_question_text TEXT,
       |    evidence TEXT,
       |    submitted_at TEXT,
       |    remarks TEXT,
       |    question_type TEXT,
       |    entity_type TEXT,
       |    entity_id TEXT,
       |    entity_name TEXT,
       |    entity_external_id TEXT,
       |    parent_one_name TEXT,
       |    parent_one_id TEXT,
       |    parent_two_name TEXT,
       |    parent_two_id TEXT,
       |    parent_three_name TEXT,
       |    parent_three_id TEXT,
       |    parent_four_name TEXT,
       |    parent_four_id TEXT,
       |    parent_five_name TEXT,
       |    parent_five_id TEXT
       |);""".stripMargin

  val createStatusTable: String =
    s"""CREATE TABLE IF NOT EXISTS @statusTable (
       |    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       |    user_id TEXT ,
       |    user_role_ids TEXT,
       |    user_roles TEXT,
       |    solution_id TEXT ,
       |    solution_name TEXT,
       |    submission_id TEXT,
       |    submission_number INTEGER,
       |    program_name TEXT,
       |    program_id TEXT,
       |    observation_name TEXT,
       |    observation_id TEXT,
       |    user_one_profile_name TEXT,
       |    user_one_profile_id TEXT,
       |    user_two_profile_name TEXT,
       |    user_two_profile_id TEXT,
       |    user_three_profile_name TEXT,
       |    user_three_profile_id TEXT,
       |    user_four_profile_name TEXT,
       |    user_four_profile_id TEXT,
       |    user_five_profile_name TEXT,
       |    user_five_profile_id TEXT,
       |    tenant_id TEXT,
       |    org_id TEXT,
       |    org_code TEXT,
       |    org_name TEXT,
       |    status_of_submission TEXT,
       |    submitted_at TEXT,
       |    entity_type TEXT,
       |    entity_id TEXT,
       |    entity_name TEXT,
       |    entity_external_id TEXT,
       |    parent_one_name TEXT,
       |    parent_one_id TEXT,
       |    parent_two_name TEXT,
       |    parent_two_id TEXT,
       |    parent_three_name TEXT,
       |    parent_three_id TEXT,
       |    parent_four_name TEXT,
       |    parent_four_id TEXT,
       |    parent_five_name TEXT,
       |    parent_five_id TEXT
       |);""".stripMargin
}